### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by luytax** [best-cost/best-cost_WPs#318]
### Identical results in geographic iteration of `attribute_health()`

In the file `testing_Rpackage` in the chunk `single exposure value with multiple uncertainties` we do an iteration using `attribute_health()` which runs without error. However in the function call the same values are used for `bhd_central, ..._lower & ..._upper` (see below)
https://github.com/best-cost/best-cost_WPs/blob/3d5b3fe6f5fc41927957df21dfbe21fac2eb1f6f/r_package/testing/testing_Rpackage.Rmd#L175-L192

When I changed the values for `bhd_lower & bhd_upper` and checked the output, the impact for `bhd_lower & bhd_upper` was always identical (see screenshot)

![image](https://github.com/user-attachments/assets/b19d085b-1933-40ae-bc9d-9608000d0c2d)

Unfortunately we didn't have any check implemented for that specific function call, so we can't know if that was always the case or whether this error got introduced at some later point after initial implementation.

@ungatoverde Can you investigate?

**Comment by ungatoverde** [comment]
Done in #337
