### ISSUE TITLE
Likely unused code in get_deaths_yll_yld()

### ISSUE THREAD

**Issue by ungatoverde** [best-cost/best-cost_WPs#370]
This code in `get_deaths_yll_yld()` seems to be unused. The if statement tell us that the code is only used if no lifetable approach is used, but the whole `get_deaths_yll_yld()` is only about this. I checked it that I did not see the function beening used for any purpose beyond lifetable. 

https://github.com/best-cost/best-cost_WPs/blob/b6611331a0cb9dd3a012c119a7aa5d3d3d4a4352/r_package/healthiar/R/get_deaths_yll_yld.R#L306-L331

@luytax Am I overlooking something? I am very surprised about it. The sex categories have to be summed but maybe they are summed somewhere else because I have deactivated the code and the results are still correct. The deactivation is provisional, I would remove the code but before I do it, I would like that four eyes look at this :-)

**Comment by luytax** [comment]
As discussed, this can be removed

**Comment by ungatoverde** [comment]
This have been removed in #374
