### ISSUE TITLE
Delete obsolete code block in `compile_input`?

### ISSUE THREAD

**Issue by luytax** [best-cost/best-cost_WPs#379]
I commented out this code in `compile_input`

https://github.com/best-cost/best-cost_WPs/blob/f3ed227c733b1cf41d39fa722656f63eed8203a4/r_package/healthiar/R/compile_input.R#L116-L122

because it caused an error for `attribute_health()` calls with `erf_eq_lower` & erf_eq_upper inputs` (e.g. in the call in the chunk `Summary uncertainty ar single geo unit erf_eq uncertainty`)

https://github.com/best-cost/best-cost_WPs/blob/f3ed227c733b1cf41d39fa722656f63eed8203a4/r_package/testing/testing_Rpackage.Rmd#L938-L950

It seems that the code is anyway incomplete/damaged (note that the statement starts with a `dplyr::mutate` without any connection to a variable.

@ungatoverde Can we delete this?

**Comment by ungatoverde** [comment]
@luytax Well spotted! You can remove the if statement because tibble ignores the lines that are NULL but you need the mutate lines. The code should be as below. Could you please correct it?

`erf_data <- # 1 x 3 tibble
          dplyr::tibble(
            exposure_name = names(erf_eq_central),
            erf_eq_central = list(erf_eq_central)),
            erf_eq_lower = list(erf_eq_lower), 
            erf_eq_upper = list(erf_eq_upper)`

**Comment by ungatoverde** [comment]
Ignore my comment above. It does not work. The if stament is needed. Otherwise error using equations in erf without lower and upper
